[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.15.31"

[[constraint]]
  branch = "master"
  name = "github.com/zmb3/spotify"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.3.0"

[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.6.0"
